# -*- coding: utf-8 -*-
"""Project2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NeCaX05EhUk-5Z5Z5mMMst9xew_Hp7i
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True) # connesione al drive

!pip install deep-translator

import joblib
import numpy as np
from deep_translator import GoogleTranslator

# ==========================================================
# 1. Carica la pipeline salvata
# ==========================================================
pipeline_path = "/content/drive/MyDrive/Project2026/pipeline.pkl"
pipeline = joblib.load(pipeline_path)

embedder = pipeline["embedder"]
scaler = pipeline["scaler"]
pca = pipeline["pca"]
clf = pipeline["classifier"]
label_encoder = pipeline["label_encoder"]

for i in range(5):
  print("QUALE FATTO VUOI DISCUTERE?")
  # ==========================================================
  # 2. Inserisci una frase da analizzare e viene tradotta per rispettare la logica dei dati di addestarmento
  # ==========================================================
  sentence1 = input()
  sentence2 = GoogleTranslator(source='auto', target='en').translate(sentence1)

  #-----------------------------------------------------------------------------------------------------------
  embedding = embedder.encode([sentence2], convert_to_numpy=True, normalize_embeddings=True)
  embedding_scaled = scaler.transform(embedding)
  embedding_pca = pca.transform(embedding_scaled)
  prediction = clf.predict(embedding_pca)
  category = label_encoder.inverse_transform(prediction)[0]

  #-----------------------------------------------------------------------------------------------------------
  print("Categoria: ", category, "\n")